<!DOCTYPE html>
<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>
<input id="pk" type="hidden"  value="<?php echo $this->publicKey; ?>"></input>


<!--=== Style Switcher ===-->    
<i class="style-switcher-btn fa fa-cogs hidden-xs"></i>
<div class="style-switcher animated fadeInRight">
    <div class="style-swticher-header">
        <div class="style-switcher-heading">Style Switcher</div>            
        <div class="theme-close"><i class="icon-close"></i></div>
    </div>

    <div class="style-swticher-body">
        <!-- Theme Colors -->
        <div class="style-switcher-heading">Theme Colors</div>
        <ul class="list-unstyled">
            <li class="theme-default theme-active" data-style="default" data-header="light"></li>
            <li class="theme-blue" data-style="blue" data-header="light"></li>
            <li class="theme-orange" data-style="orange" data-header="light"></li>
            <li class="theme-red" data-style="red" data-header="light"></li>
            <li class="theme-light" data-style="light" data-header="light"></li>
            <li class="theme-purple last" data-style="purple" data-header="light"></li>
            <li class="theme-aqua" data-style="aqua" data-header="light"></li>
            <li class="theme-brown" data-style="brown" data-header="light"></li>
            <li class="theme-dark-blue" data-style="dark-blue" data-header="light"></li>
            <li class="theme-light-green" data-style="light-green" data-header="light"></li>
            <li class="theme-dark-red" data-style="dark-red" data-header="light"></li>
            <li class="theme-teal last" data-style="teal" data-header="light"></li>
        </ul>

        <!-- Theme Skins -->
        <div class="style-switcher-heading">Theme Skins</div>
        <div class="row no-col-space margin-bottom-20 skins-section">
            <div class="col-xs-6">
                <button data-skins="default" class="btn-u btn-u-xs btn-u-dark btn-block active-switcher-btn handle-skins-btn">Light</button>
            </div>
            <div class="col-xs-6">
                <button data-skins="dark" class="btn-u btn-u-xs btn-u-dark btn-block skins-btn">Dark</button>
            </div>
        </div>            

        <hr>

        <!-- Layout Styles -->
        <div class="style-switcher-heading">Layout Styles</div>
        <div class="row no-col-space margin-bottom-20">
            <div class="col-xs-6">
                <a href="javascript:void(0);" class="btn-u btn-u-xs btn-u-dark btn-block active-switcher-btn wide-layout-btn">Wide</a>                
            </div>
            <div class="col-xs-6">
                <a href="javascript:void(0);" class="btn-u btn-u-xs btn-u-dark btn-block boxed-layout-btn">Boxed</a>                
            </div>
        </div>            

        <hr>

        <!-- Theme Type -->
        <div class="style-switcher-heading">Theme Types and Versions</div>
        <div class="row no-col-space margin-bottom-10">
            <div class="col-xs-6">
                <a href="Shop-UI/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">Shop UI <small class="dp-block">Template</small></a>
            </div>
            <div class="col-xs-6">
                <a href="One-Page/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">One Page <small class="dp-block">Template</small></a>
            </div>
        </div>           

        <div class="row no-col-space">
            <div class="col-xs-6">
                <a href="Blog/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">Blog <small class="dp-block">Template</small></a>
            </div>
            <div class="col-xs-6">
                <a href="RTL/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">RTL <small class="dp-block">Version</small></a>
            </div>
        </div>           
    </div>
</div><!--/style-switcher-->
<!--=== End Style Switcher ===-->    

<div class="wrapper">
    <!--=== Header ===-->    
    <div class="header">
        <div class="container">
            <!-- Logo -->
            <a class="logo" href="index-2.html">
                <img src="<?php echo $this->basePath('onyuz/standard/assets/img/logo1-default.png') ?>" alt="Logo">
            </a>
            <!-- End Logo -->

            <!-- Topbar -->
            <div class="topbar">
                <ul style="background: #ddd;
                    padding: 10px;" class="loginbar pull-right">
                    <li class="hoverSelector">
                        <i class="fa fa-globe"></i>
                        <a><?php echo $this->translate('Languages') ?> </a>
                        <ul id='topLanguageBar' class="languages hoverSelectorBlock">                                    
                        </ul>
                    </li>
                    <li class="topbar-devider"></li>   
                    <li><a href="page_faq.html"><?php echo $this->translate('Help') ?></a></li>  
                    <li class="topbar-devider"></li>   
                    <li><a href="<?php echo $this->url('login', array('action' => 'logout')); ?>"><?php echo $this->translate('Log out') ?></a></li>   
                </ul>
            </div>
            <!-- End Topbar -->

            <!-- Toggle get grouped for better mobile display -->
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="fa fa-bars"></span>
            </button>
            <!-- End Toggle -->
        </div><!--/end container-->

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse menu-xs navbar-responsive-collapse" >
            <div class="container">
                <ul class="nav navbar-nav " style="font-size: 10px;">
                    <li class="page-scroll home">
                        <a href="#body"><?php echo $this->translate('Home') ?></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#about"><?php echo $this->translate('About Us') ?></a>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                            <?php echo $this->translate('Services') ?>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="page-scroll"><a href="#body">
                                    <?php echo $this->translate('OSTIM Services') ?></a>
                            </li>
                        </ul>
                    </li>
                    <li class="page-scroll">
                        <a href="#news"><?php echo $this->translate('News') ?></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#contact"><?php echo $this->translate('Contacts') ?></a>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                            <?php echo $this->translate('Submenus') ?>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="page-scroll">
                                <a href="#body"><?php echo $this->translate('Home') ?></a>
                            </li>
                            <li class="page-scroll">
                                <a href="../index-2.html"><?php echo $this->translate('Main') ?></a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div><!--/end container-->
        </div><!--/navbar-collapse-->
    </div>
    <!--=== End Header ===-->


    <!--=== Breadcrumbs ===-->
    <div class="breadcrumbs">
        <!--<div style='background: #FAF8F0;' class="container">--> 
        <div style='background: #E0EDDF;' class="container">
            <h1 class="pull-left"><i class="fa fa-user"></i><?php echo $this->translate('Company Name') ?></h1>
            <ul class="pull-right breadcrumb">                        
                <li><a href="/ostim/sanalfabrika"><?php echo $this->translate('Home') ?></a></li>
                <li><?php echo $this->translate('Company Profile') ?></li>
                <li class="active"><?php echo $this->translate('Performance Meters') ?></li>
            </ul>
        </div>
    </div><!--/breadcrumbs-->
    <!--=== End Breadcrumbs ===-->


    <!--=== Profile ===-->
    <div class="container content profile">
        <div class="row">
            <!--Left Sidebar-->
            <div class="col-md-3 md-margin-bottom-40">
                <img class="img-responsive profile-img margin-bottom-20" 
                     src="<?php echo $this->basePath('onyuz/standard/assets/img/clients2/emge-logo-without-background.png') ?>" alt="">

                <ul class="list-group sidebar-nav-v1 margin-bottom-40" id="sidebar-nav-1">
                    <li class="list-group-item">
                        <a href="companyprofile"><i class="fa fa-info"></i> <?php echo $this->translate('Company Profile') ?></a>
                    </li>
                    <li class="list-group-item active" >
                        <a href="companyperformancemetersprofile"><i class="fa fa-bar-chart-o"></i> <?php echo $this->translate('Performance Meters') ?></a>
                    </li>
                    <li class="list-group-item">
                        <a href="companyproductsprofile"><i class="fa fa-automobile"></i> <?php echo $this->translate('Products') ?></a>
                    </li>
                    <li class="list-group-item">
                        <a href="companymembersprofile"><i class="fa fa-group"></i> <?php echo $this->translate('Members') ?></a>
                    </li>                                        
                    <li class="list-group-item">
                        <a href="companyprojectsprofile"><i class="fa fa-cubes"></i> <?php echo $this->translate('Projects') ?></a>
                    </li>
                    <li class="list-group-item">
                        <a href="companycommentsprofile"><i class="fa fa-comments"></i> <?php echo $this->translate('Comments') ?></a>
                    </li>                                        
                    <li class="list-group-item">
                        <a href="companyhistoryprofile"><i class="fa fa-history"></i> <?php echo $this->translate('History') ?></a>
                    </li>                                       
                    <li class="list-group-item">
                        <a href="companyprofilesettings"><i class="fa fa-cog"></i> <?php echo $this->translate('Settings') ?></a>
                    </li> 
                </ul>     

                <div class="panel-heading-v2 overflow-h">
                    <h2 class="heading-xs pull-left"><i class="fa fa-bar-chart-o"></i> Task Progress</h2>
                    <a href="#"><i class="fa fa-cog pull-right"></i></a>
                </div>
                <h3 class="heading-xs">Web Design <span class="pull-right">92%</span></h3>
                <div class="progress progress-u progress-xxs">
                    <div style="width: 92%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="92" role="progressbar" class="progress-bar progress-bar-u">
                    </div>
                </div>
                <h3 class="heading-xs">Unify Project <span class="pull-right">85%</span></h3>
                <div class="progress progress-u progress-xxs">
                    <div style="width: 85%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="85" role="progressbar" class="progress-bar progress-bar-blue">
                    </div>
                </div>
                <h3 class="heading-xs">Sony Corporation <span class="pull-right">64%</span></h3>
                <div class="progress progress-u progress-xxs margin-bottom-40">
                    <div style="width: 64%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="64" role="progressbar" class="progress-bar progress-bar-dark">
                    </div>
                </div>

                <hr>

                <!--Notification-->
                <div class="panel-heading-v2 overflow-h">
                    <h2 class="heading-xs pull-left"><i class="fa fa-bell-o"></i> <?php echo $this->translate('Notification') ?></h2>
                    <a href="#"><i class="fa fa-cog pull-right"></i></a>
                </div>
                <ul class="list-unstyled mCustomScrollbar margin-bottom-20" data-mcs-theme="minimal-dark">
                    <li class="notification">
                        <i class="icon-custom icon-sm rounded-x icon-bg-red icon-line icon-envelope"></i>
                        <div class="overflow-h">
                            <span><strong>Albert Heller</strong> has sent you email.</span>
                            <small>Two minutes ago</small>
                        </div>    
                    </li>
                    <li class="notification">
                        <img class="rounded-x" src="<?php echo $this->basePath('onyuz/assets/img/testimonials/img6.jpg') ?>" alt="">
                        <div class="overflow-h">
                            <span><strong>Taylor Lee</strong> started following you.</span>
                            <small>Today 18:25 pm</small>
                        </div>    
                    </li>
                    <li class="notification">
                        <i class="icon-custom icon-sm rounded-x icon-bg-yellow icon-line fa fa-bolt"></i>
                        <div class="overflow-h">
                            <span><strong>Natasha Kolnikova</strong> accepted your invitation.</span>
                            <small>Yesterday 1:07 pm</small>
                        </div>    
                    </li>
                    <li class="notification">
                        <img class="rounded-x" src="<?php echo $this->basePath('onyuz/assets/img/testimonials/img1.jpg') ?>" alt="">
                        <div class="overflow-h">
                            <span><strong>Mikel Andrews</strong> commented on your Timeline.</span>
                            <small>23/12 11:01 am</small>
                        </div>    
                    </li>
                    <li class="notification">
                        <i class="icon-custom icon-sm rounded-x icon-bg-blue icon-line fa fa-comments"></i>
                        <div class="overflow-h">
                            <span><strong>Bruno Js.</strong> added you to group chating.</span>
                            <small>Yesterday 1:07 pm</small>
                        </div>    
                    </li>
                    <li class="notification">
                        <img class="rounded-x" src="<?php echo $this->basePath('onyuz/assets/img/testimonials/img6.jpg') ?>" alt="">
                        <div class="overflow-h">
                            <span><strong>Taylor Lee</strong> changed profile picture.</span>
                            <small>23/12 15:15 pm</small>
                        </div>    
                    </li>
                </ul>    

            </div>
            <!--End Left Sidebar-->

            <!-- Counter header start -->
            <div class="col-md-9" style="padding-bottom: 20px">
                <!--<div class="parallax-counter-v4 parallaxBg">-->
                <!--Service Block v3-->
                <div class="row margin-bottom-10">


                    <div class="col-sm-6 sm-margin-bottom-20">
                        <div class="service-block-v3 service-block-aviation">
                            <i class="icon-plane"></i>
                            <span class="service-heading"><?php echo $this->translate('Submitted Aviation Projects') ?></span>
                            <span class="counter">358</span>

                            <div class="clearfix margin-bottom-10"></div>

                            <div class="row margin-bottom-20">
                                <div class="col-xs-6 service-in">
                                    <small><?php echo $this->translate('Last Week') ?></small>
                                    <h4 class="counter">25</h4>
                                </div>
                                <div class="col-xs-6 text-right service-in">
                                    <small><?php echo $this->translate('Last Month') ?></small>
                                    <h4 class="counter">114</h4>
                                </div>
                            </div>
                            <div class="statistics">
                                <h3 class="heading-xs"><?php echo $this->translate('Statistics in Progress Bar') ?><span class="pull-right">67%</span></h3>
                                <div class="progress progress-u progress-xxs">
                                    <div style="width: 67%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="67" role="progressbar" class="progress-bar progress-bar-light">
                                    </div>
                                </div>
                                <small>11% less <strong><?php echo $this->translate('than last month') ?></strong></small>
                            </div>            
                        </div>
                    </div>


                    <div class="col-sm-6">
                        <div class="service-block-v3 service-block-renewable">
                            <i class="icon-energy"></i>
                            <span class="service-heading"><?php echo $this->translate('Submitted Renewable Energy Projects') ?></span>
                            <span class="counter">324,056</span>

                            <div class="clearfix margin-bottom-10"></div>

                            <div class="row margin-bottom-20">
                                <div class="col-xs-6 service-in">
                                    <small><?php echo $this->translate('Last Week') ?></small>
                                    <h4 class="counter">26,904</h4>
                                </div>
                                <div class="col-xs-6 text-right service-in">
                                    <small><?php echo $this->translate('Last Month') ?></small>
                                    <h4 class="counter">124,766</h4>
                                </div>
                            </div>
                            <div class="statistics">
                                <h3 class="heading-xs"><?php echo $this->translate('Statistics in Progress Bar') ?><span class="pull-right">89%</span></h3>
                                <div class="progress progress-u progress-xxs">
                                    <div style="width: 89%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="89" role="progressbar" class="progress-bar progress-bar-light">
                                    </div>
                                </div>
                                <small>15% <?php echo $this->translate('higher') ?> <strong><?php echo $this->translate('than last month') ?></strong></small>
                            </div>            
                        </div>
                    </div>
                </div><!--/end row-->
                <!--End Service Block v3-->                    
                <!--</div>-->
            </div>

            <!-- Counter header ends -->

            <!-- Profile Content -->            
            <div class="col-md-9">


                <div class="profile-body">
                    <div class="block-description">
                        <div class="container">
                            <i class="center-icon rounded-x fa fa-edit"></i>
                            <div class="title-box-v2 col-md-8">
                                <h2>Company Performance Meters</h2>
                                <p>Pellentesque et erat ac massa cursus porttitor eget sed magna.</p>
                            </div> 
                            <div class="row">
                                <div class="col-md-8"> 
                                    <div class="left-inner">
                                        
                                        <h3>Overview</h3>
                                        
                                        <div class="row">
                                            <!-- Overview -->
                                            <div class="col-sm-6">
                                                <div class="overview">
                                                    <i class="fa fa-user"></i>
                                                    <div class="overflow-h">
                                                        <small><?php echo $this->translate('Engineers')?></small>
                                                        <small>20</small>
                                                        <div class="progress progress-u progress-xxs">
                                                            <div style="width: 15%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="15" role="progressbar" class="progress-bar progress-bar-u">
                                                            </div>
                                                        </div>
                                                    </div>    
                                                </div>
                                            </div>
                                            <!-- End Overview -->

                                            <!-- Overview -->
                                            <div class="col-sm-6">
                                                <div class="overview">
                                                    <i class="fa fa-share"></i>
                                                    <div class="overflow-h">
                                                        <small><?php echo $this->translate('Machine Tools')?></small>
                                                        <small>100</small>
                                                        <div class="progress progress-u progress-xxs">
                                                            <div style="width: 100%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="100" role="progressbar" class="progress-bar progress-bar-u">
                                                            </div>
                                                        </div>
                                                    </div>    
                                                </div>
                                            </div>
                                            <!-- End Overview -->
                                        </div>

                                        <div class="row margin-bottom-20">
                                            <!-- Overview -->
                                            <div class="col-sm-6">
                                                <div class="overview">
                                                    <i class="fa fa-eye"></i>
                                                    <div class="overflow-h">
                                                        <small><?php echo $this->translate('Technicians')?></small>
                                                        <small>70</small>
                                                        <div class="progress progress-u progress-xxs">
                                                            <div style="width: 35%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="35" role="progressbar" class="progress-bar progress-bar-u">
                                                            </div>
                                                        </div>
                                                    </div>    
                                                </div>
                                            </div>
                                            <!-- End Overview -->

                                            <!-- Overview -->
                                            <div class="col-sm-6">
                                                <div class="overview">
                                                    <i class="fa fa-group"></i>
                                                    <div class="overflow-h">
                                                        <small><?php echo $this->translate('Number of Employee')?></small>
                                                        <small>210</small>
                                                        <div class="progress progress-u progress-xxs">
                                                            <div style="width: 100%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="100" role="progressbar" class="progress-bar progress-bar-u">
                                                            </div>
                                                        </div>
                                                    </div>    
                                                </div>
                                            </div>
                                        </div>
                                           
                                        <hr>
                                        
                                        <div class="left-inner">
                                         
                                        <h3><?php echo $this->translate('Company Meters')?></h3>
                                        <!-- Pie Chart Progress Bar -->    
                                        <div class="row margin-bottom-20">
                                            <div class="p-chart col-sm-6 col-xs-6 sm-margin-bottom-10">
                                                <h3><?php echo $this->translate('Company Quality Performance') ?></h3>
                                                <div class="circle" id="circle-4"></div>
                                            </div>
                                            <div class="p-chart col-sm-6 col-xs-6">                                                    
                                                <button class="btn-u btn-u-xs btn-block btn-u-default box-shadow-Outset" 
                                                        onclick="qualityHistory()" type="button">
                                                            <?php echo $this->translate('Last Year Increase Ratio') ?>
                                                </button>                                                    
                                                <button class="btn-u btn-u-xs btn-block btn-u-default box-shadow-Outset" 
                                                        onclick="qualityPerformances()" type="button">
                                                            <?php echo $this->translate('Overall Performance') ?>
                                                </button>                                                    
                                                <button class="btn-u btn-u-xs btn-block btn-u-default box-shadow-Outset" 
                                                        onclick="listOfCertificates()" type="button">
                                                            <?php echo $this->translate('Available Quality Certificates and Standards') ?>
                                                </button>                                                    
                                            </div> 
                                        </div>
                                        <div id="qualityDetaildDIV" 
                                             class="row margin-bottom-20 left-inner" style="display:none" >
                                            <hr>
                                            <div id="qualityDetailsInsideDIV" class="left-inner" >
                                                
                                            </div>
                                            <hr>
                                        </div>
                                        <div class="row margin-bottom-20">
                                            <div class="p-chart col-sm-6 col-xs-4">
                                                <h3><?php echo $this->translate('Project Completion Performance') ?></h3>
                                                <div class="circle" id="circle-5"></div>
                                            </div>
                                            <div class="p-chart col-sm-6 col-xs-6 sm-margin-bottom-10">
                                                <button class="btn-u btn-u-xs btn-block btn-u-default box-shadow-Outset" 
                                                        onclick="performanceDetails()" type="button">
                                                            <?php echo $this->translate('Contributed Projects') ?>
                                                </button>                                                    
                                                <button class="btn-u btn-u-xs btn-block btn-u-default box-shadow-Outset" 
                                                        onclick="performanceDetails()" type="button">
                                                            <?php echo $this->translate('Accomplished Successfully') ?>
                                                </button>                                                    
                                                <button class="btn-u btn-u-xs btn-block btn-u-default box-shadow-Outset" 
                                                        onclick="performanceDetails()" type="button">
                                                            <?php echo $this->translate('Unfinished Porjects') ?>
                                                </button>                                                     
                                                <button class="btn-u btn-u-xs btn-block btn-u-default box-shadow-Outset" 
                                                        onclick="performanceDetails()" type="button">
                                                            <?php echo $this->translate('Projects in Progress') ?>
                                                </button>                                                   
                                            </div>       
                                        </div>
                                        <div id="pastPerformanceDetailsDIV" 
                                             class="row margin-bottom-20 left-inner" style="display:none" >
                                            <hr>
                                            <div id="pastPerformanceDetailsInsideDIV" class="left-inner" >
                                                
                                            </div>
                                            <hr>
                                        </div>
                                        <div class="row margin-bottom-20">
                                            <div class="p-chart col-sm-6 col-xs-6">
                                                <h3><?php echo $this->translate('Customer Satisfaction Rate') ?></h3>
                                                <div class="circle" id="circle-10"></div>
                                            </div>
                                            <div class="p-chart col-sm-6 col-xs-6 sm-margin-bottom-10">
                                               <button class="btn-u btn-u-xs btn-block btn-u-default box-shadow-Outset" 
                                                        onclick="customerDetails()" type="button">
                                                            <?php echo $this->translate('Consent Customers') ?>
                                                </button>                                                    
                                                <button class="btn-u btn-u-xs btn-block btn-u-default box-shadow-Outset" 
                                                        onclick="customerDetails()" type="button">
                                                            <?php echo $this->translate('Complained Customers') ?>
                                                </button>                                                    
                                                <button class="btn-u btn-u-xs btn-block btn-u-default box-shadow-Outset" 
                                                        onclick="customerDetails()" type="button">
                                                            <?php echo $this->translate('Unfinished Porjects') ?>
                                                </button>                                                     
                                                <button class="btn-u btn-u-xs btn-block btn-u-default box-shadow-Outset" 
                                                        onclick="customerDetails()" type="button">
                                                            <?php echo $this->translate('Projects in Progress') ?>
                                                </button>                                                  
                                            </div>       
                                        </div>
                                        <div id="customerDetailsDIV" 
                                             class="row margin-bottom-20 left-inner" style="display:none" >
                                            <hr>
                                            <div id="customerDetailsInsideDIV" class="left-inner" >
                                                
                                            </div>
                                            <hr>
                                        </div>

                                        <!-- End Pie Chart Progress Bar -->
                                        
                                        </div>
                                        
                                        <hr>

                                        <h3>Latest Recommendations</h3>
                                        <div class="people-say margin-bottom-20">
                                            <img src="<?php echo $this->basePath('onyuz/standard/assets/img/testimonials/img2.jpg') ?>" alt="">
                                            <div class="overflow-h">
                                                <span>Eva Maria Kl.</span>
                                                <small class="hex pull-right">5 - hours ago</small>
                                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis varius hendrerit nisl id condimentum.</p>
                                            </div>    
                                        </div>

                                        <div class="people-say margin-bottom-20">
                                            <img src="<?php echo $this->basePath('onyuz/standard/assets/img/testimonials/user.jpg') ?>" alt="">
                                            <div class="overflow-h">
                                                <span>Christian Draxler</span>
                                                <small class="hex pull-right">2 - days ago</small>
                                                <p>Vestibulum justo est, pharetra fermentum justo in, tincidunt mollis turpis. Duis imperdiet non justo euismod semper.</p>
                                            </div>    
                                        </div>

                                        <div class="people-say">
                                            <img src="<?php echo $this->basePath('onyuz/standard/assets/img/testimonials/img3.jpg') ?>" alt="">
                                            <div class="overflow-h">
                                                <span>Alex Taylor</span>
                                                <small class="hex pull-right">3 - days ago</small>
                                                <p>A Wal-Mart cashier is responsible for effectively executing and adhering to the “Basic Beliefs” of the founder.</p>
                                            </div>    
                                        </div>

                                        <hr> 

                                    </div>   
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Profile Content -->            
        </div>
    </div><!--/container-->    
    <!--=== End Profile ===-->

    <!--=== Footer Version 1 ===-->
    <div class="footer-v1">
        <div class="footer">
            <div class="container">
                <div class="row">
                    <!-- About -->
                    <div class="col-md-3 md-margin-bottom-40">
                        <a href="index-2.html"><img id="logo-footer" class="footer-logo" 
                                                    src="<?php echo $this->basePath('onyuz/standard/assets/img/logo2-default.png') ?>" 
                                                    alt=""></a>
                        <p><?php
                            echo $this->translate('A virtual enterprise (VE) is a temporary alliance of '
                                    . 'businesses that come together to share skills or core competencies and resources '
                                    . 'in order to better respond to business opportunities, and whose cooperation is '
                                    . 'supported by computer networks.')
                            ?></p>
                    </div><!--/col-md-3-->
                    <!-- End About -->

                    <!-- Latest -->
                    <div class="col-md-3 md-margin-bottom-40">
                        <div class="posts">
                            <div class="headline"><h2><?php echo $this->translate('Latest Posts') ?></h2></div>
                            <ul class="list-unstyled latest-list">
                                <li>
                                    <a href="#"><?php echo $this->translate('Latest News about OSTIM VE') ?></a>
                                    <small><?php echo $this->translate('February') ?> 8, 2016</small>
                                </li>
                                <li>
                                    <a href="#"><?php echo $this->translate('OSTIM Clusters News') ?></a>
                                    <small><?php echo $this->translate('January') ?> 23, 2016</small>
                                </li>
                                <li>
                                    <a href="#"><?php echo $this->translate('New Project Calls') ?></a>
                                    <small><?php echo $this->translate('December') ?> 15, 2016</small>
                                </li>
                            </ul>
                        </div>
                    </div><!--/col-md-3-->  
                    <!-- End Latest --> 

                    <!-- Link List -->
                    <div class="col-md-3 md-margin-bottom-40">
                        <div class="headline"><h2><?php echo $this->translate('Useful Links') ?></h2></div>
                        <ul class="list-unstyled link-list">
                            <li><a href="http://www.ostim.org.tr/"><?php echo $this->translate('Ostim Organized Industrial Zone') ?></a><i class="fa fa-angle-right"></i></li>
                            <li><a href="http://www.sanayi.gov.tr/"><?php echo $this->translate('Turkish Ministry of SIT') ?></a><i class="fa fa-angle-right"></i></li>
                            <li><a href="https://www.tubitak.gov.tr/"><?php echo $this->translate('TUBITAK') ?></a><i class="fa fa-angle-right"></i></li>
                            <li><a href="http://www.kosgeb.gov.tr/"><?php echo $this->translate('KOSGEB') ?></a><i class="fa fa-angle-right"></i></li>
                            <!--<li><a href="#"><?php echo $this->translate('') ?></a><i class="fa fa-angle-right"></i></li>-->
                        </ul>
                    </div><!--/col-md-3-->
                    <!-- End Link List -->                    

                    <!-- Address -->
                    <div class="col-md-3 map-img md-margin-bottom-40">
                        <div class="headline"><h2><?php echo $this->translate('Contact Us') ?></h2></div>                         
                        <address class="md-margin-bottom-40">
                            100. Yıl Bulvarı No: 101/A <br />
                            OSTIM, Ankara <br />
                            Turkey <br />
                            <?php echo $this->translate('Phone') ?> :  +90 312 385 50 90 <br />
                            <?php echo $this->translate('Fax') ?>:    +90 312 354 58 98 <br />
                            <?php echo $this->translate('Email') ?>: <a href="mailto:info@ostim.com.tr" class="">info@ostim.com.tr</a>
                        </address>
                    </div><!--/col-md-3-->
                    <!-- End Address -->
                </div>
            </div> 
        </div><!--/footer-->

        <div class="copyright">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">                     
                        <p>
                            2016 &copy; <?php echo $this->translate('All Rights Reserved.') ?>
                            <a href="#"><?php echo $this->translate('Privacy Policy') ?></a> | <a href="#"><?php echo $this->translate('Terms of Service') ?></a>
                        </p>
                    </div>

                    <!-- Social Links -->
                    <div class="col-md-6">
                        <ul class="footer-socials list-inline">
                            <li>
                                <a href="https://www.facebook.com/OstimOSB/" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Facebook">
                                    <i class="fa fa-facebook"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Skype">
                                    <i class="fa fa-skype"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://plus.google.com/+OST%C4%B0MOSB1967" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Google Plus">
                                    <i class="fa fa-google-plus"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://www.linkedin.com/in/ostim-osb-2b94b847" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Linkedin">
                                    <i class="fa fa-linkedin"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://www.instagram.com/ostimosb/" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Instagram">
                                    <i class="fa fa-instagram"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://twitter.com/ostimosb" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Twitter">
                                    <i class="fa fa-twitter"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Dribbble">
                                    <i class="fa fa-dribbble"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <!-- End Social Links -->
                </div>
            </div> 
        </div><!--/copyright-->
    </div>        
    <!--=== End Footer Version 1 ===-->
</div><!--/wrapper-->